### ISSUE TITLE
Attaching to a paused container causes a thrown exception

### ISSUE THREAD

**Issue by boucher** [mcollina/docker-loghose#11]
Related to this ticket: https://github.com/mcollina/docker-allcontainers/pull/7

I'm using docker-loghose to stream the logs of all my containers, but when restarting my log watcher, some of the watched containers are paused. That issue alone is fixed in the referenced docker-allcontainers issue, but I've now got an issue with a container that unpauses and then pauses again too quickly for docker-loghose to attach (or at least, that's what seems to be happening currently). 

Unfortunately, because of the throw in the callback to container.attach, there's no way to easily handle this situation. One solution might be an error handler as a constructor option?

**Comment by cammellos** [comment]
Hi,
Thanks for reporting the issue,
I guess having an error callback is an option, what do you think @mcollina?

**Comment by mcollina** [comment]
You mean https://github.com/mcollina/docker-loghose/blob/master/lib/loghose.js#L44-L46?

The error handling need to be redesigned to handle this case. You can't _just_ add a callback, because that could be called unlimited amount of times. We could `'error'` the stream, but that would not help either, because this error is recoverable. So, we should possibly emit a custom event here, and recover somehow from that error.

Would you send a PR?

**Comment by boucher** [comment]
One unfortunate aspect of the way loghose and allcontainers interact is that it's essentially not possible to deal with this situation; allcontainers would need to know about the failure (or, would at least need to pass pause/unpause events along). It may be uncommon, and not worth trying to make work.

**Comment by mcollina** [comment]
@boucher can you please iterate on this more?
What is missing?

**Comment by boucher** [comment]
Imagine the following scenario:

```
> docker ps
abc    paused
def     running

# obviously this is simplified
> node docker-loghose 

# simultaneously
> docker unpause abc
> docker pause abc
```

If you were logging everything, you might see a sequence of events like this:

```
allcontainers: starting up
allcontainers: abc is paused, will emit "start" on unpause
allcontainers: emit "start" on def
loghose: got "start", attach to def
>>>> the interesting part
docker: unpause "abc"
allcontainers: abc was unpaused, emit "start" on abc
docker: pause "abc"
loghose: got "start", attach to abc
>>>>>> THROW abc is paused
```

This is the bug I have. Once `allcontainers` has emitted the `start` event, it will never emit start again. But, even if there's a way to catch and handle the `attach` failure by `loghose`, there's not enough information available to actually retry attaching to `abc` next time it unpauses. It seems like you'd actually just have to start listening to the docker event stream yourself and parsing all the unpause events.

**Comment by mcollina** [comment]
I think the best solution is for `allcontainers` to report the full lifecycle events.
Or maybe remap "pause" and "unpause" as start and stop events.

Might that work?

**Comment by boucher** [comment]
Yeah, I think that would work, unless someone is relying on the behavior of just watching start/stop to track which containers are running.

**Comment by mcollina** [comment]
why? If paused it's not executing.
Il giorno mar 10 mag 2016 alle 19:07 Ross Boucher notifications@github.com
ha scritto:

**Comment by boucher** [comment]
Well, you could imagine that I wanted to, say, keep track of all the currently assigned ports, and doing that by watching start/stop events. Even though a container is paused, its network resources are still allocated (as are other things). 

I think firing separate pause/unpause events would be more flexible and have less potential impact (though, looking at actual use in public npm packages, nothing seems like it would be obviously affected here).

**Comment by mcollina** [comment]
I think this is fixed now. Please check and reopen if needed.
