### ISSUE TITLE
Remove filter for current container

### ISSUE THREAD

**Issue by megastef** [mcollina/docker-loghose#12]
This line makes it impossible to catch logs from a container using docker-loghose API: 
 https://github.com/mcollina/docker-loghose/blob/cb576fb345772cf98bf56beb6906e821ed8c4500/lib/loghose.js#L39

An endless loop would only be crated if the application, would dump  the received logs to console. This is not given in our application, because it forwards logs to a storage backend. 

The workaround is to change process.env.HOSTNAME=process.env.HOSTNAME+'_' before dockercloghose constructor. I think we don't want such hacks ... and the option should be in the constructor. Hmm, but we have such options already! E.g. setting filters with 'skipByImage'. 
The docker-loghose CLI tool, running in a container should be changed and not the API itself. 

See also: https://github.com/pelger/docker-stats/issues/9  - which is probaly a copy/paste from docker-loghose code.

**Comment by mcollina** [comment]
Merged, releasing soon
