### ISSUE TITLE
Test fails on node.js v6.x

### ISSUE THREAD

**Issue by megastef** [mcollina/docker-loghose#14]
It seems that something in the buffer API did change, parser tests fail when with `npm test` e.g.:

```
9) The parser outputs the chunk wrapped in an object:
     Error: If encoding is specified then the first argument must be a string
      at new Buffer (buffer.js:106:13)
      at Object.module.exports.buildBuffer (test/helper.js:28:16)
      at Context.<anonymous> (test/parser/parser.js:25:44)
      at Context.<anonymous> (test/parser/parser.js:14:5)

```

@cammellos, could you pls. look into it?  I think only the parser test is wrong, I had no issues with node version 6.x and docker-loghose. 

Once this works, we could update .travis.yml for Node 6.

**Comment by cammellos** [comment]
Sure, I should be able to have a look at it this weeked, thanks!

**Comment by megastef** [comment]
Made it easy for you, tests passing on Node v6 with this change. Pls review:
https://github.com/mcollina/docker-loghose/pull/13/commits/8be900d45c50313fb32d90fd289769b7f4475d35

**Comment by megastef** [comment]
Better look at https://github.com/mcollina/docker-loghose/pull/13/commits/6fe138465576d800b480c55c75fc74124125a279 :) the previous did fail on node 0.10. Part of this PR https://github.com/mcollina/docker-loghose/pull/13 - please comment there if anything is wrong with the changes in helper.js

**Comment by megastef** [comment]
Solved with https://github.com/mcollina/docker-loghose/pull/13
