### ISSUE TITLE
Container does not exists anymore

### ISSUE THREAD

**Issue by megastef** [mcollina/docker-loghose#17]
Hi, I see problem in following lines, where errors are thrown but not handled anywhere (as far I see):
https://github.com/mcollina/docker-loghose/blob/master/lib/loghose.js#L45
https://github.com/mcollina/docker-loghose/blob/master/lib/loghose.js#L50

There is no error handler or try/catch here: 
https://github.com/mcollina/docker-loghose/blob/master/lib/loghose.js#L21

My question:
- Why throw an error, when there is no option to install an error event listener?  Or does such an option exist? If yes, how could I create an error handler for it (in a library using docker-loghose)? 
- In case the docker-inspect call or attach fails, it could be simply ignored, by a return in the attach functions? The container might be killed already  ...

Origin of this issue: https://github.com/sematext/sematext-agent-docker/issues/14

**Comment by megastef** [comment]
How will through2 deal with the error? Emit an error object to the stream?

**Comment by megastef** [comment]
duplicate of #11 ?

**Comment by mcollina** [comment]
It should be fixed now, reopen if needed.
