### ISSUE TITLE
[Feature] Implement container tag support

### ISSUE THREAD

**Issue by hazcod** [mcollina/docker-loghose#19]
Original issue: https://github.com/rapid7/docker-logentries/issues/45

When using an orchestrator, it's difficult to know what application stack (or equivalent construct) a container belongs to if it has a UUID-style name, as is common in that use case. The image is kinda helpful, except when they're not, e.g., common database images. Docker engine now supports labels, which are accessible via the API and could be included in the stats/event output to help gather more useful context.

**Comment by mcollina** [comment]
@HazCod I'll be happy to review and merge a PR that add support for those.

**Comment by hazcod** [comment]
PR in docker-allcontainers ; https://github.com/mcollina/docker-allcontainers/pull/13

**Comment by hazcod** [comment]
Pull Request: https://github.com/mcollina/docker-loghose/pull/20
