### ISSUE TITLE
v1.0.0

### ISSUE THREAD

**Issue by mcollina** [mcollina/docker-loghose#8]
Should we graduate docker-loghose to v1.0.0? It seem quite stable.

cc @megastef @cammellos 

also @megastef would you like to become a collaborator here?

**Comment by megastef** [comment]
2 x Yes, docker-loghose looks pretty stable. 

We use docker-loghose in production for [Sematext Agent Docker](https://github.com/sematext/sematext-agent-docker) - and we have to switch over to local repositories in case of hot fixes for our docker image ... so helping out here could save us some time.

**Comment by mcollina** [comment]
@megastef I've add you as a collaborator.

Any other opinion on the matter?

**Comment by cammellos** [comment]
Hi, sounds good to me! Cheers

**Comment by mcollina** [comment]
Blocked by https://github.com/mcollina/docker-loghose/pull/9

**Comment by megastef** [comment]
Solved by https://github.com/mcollina/docker-loghose/pull/10
In addtion a bit of tuning: https://github.com/mcollina/docker-loghose/commit/68d87bcebe1c4f5d35f043b0006dcbda39b1cac9
Buffer.byteLength() is ~3 times faster then new Buffer().length and reduces memory usage and garbage collection.

**Comment by megastef** [comment]
Finally the README got a working example and latest format specifications https://github.com/mcollina/docker-loghose/commit/a9acf5b7e740435d3565fc154babb54be5183b14

**Comment by mcollina** [comment]
Released 1.0.0
